<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ejercicio 1</title>
</head>
<body>
    <?php
    $i = 0;

    while ($i < 10) {
        $i++;
        echo "Tabla del $i";
        echo "<br/>";
        echo "**************";
        echo "<br/>";
        echo "$i X 1 = ". $i * 1;
        echo "<br/>";
        echo "$i X 2 = ". $i * 2;
        echo "<br/>";
        echo "$i X 3 = ". $i * 3;
        echo "<br/>";
        echo "$i X 4 = ". $i * 4;
        echo "<br/>";
        echo "$i X 5 = ". $i * 5;
        echo "<br/>";
        echo "$i X 6 = ". $i * 6;
        echo "<br/>";
        echo "$i X 7 = ". $i * 7;
        echo "<br/>";
        echo "$i X 8 = ". $i * 8;
        echo "<br/>";
        echo "$i X 9 = ". $i * 9;
        echo "<br/>";
        echo "$i X 10 = ". $i * 10;
        echo "<br/>";
        echo ".......";
        echo "<br/>";
        echo "<br/>";
    }
    ?>
</body>
</html>